apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-html
  namespace: hello-world
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/part-of: ztc-examples
    example: "true"
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Zero Touch Cluster - Hello World</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                text-align: center;
                padding: 50px;
                margin: 0;
            }
            .container {
                max-width: 600px;
                margin: 0 auto;
                background: rgba(255, 255, 255, 0.1);
                padding: 40px;
                border-radius: 15px;
                box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
            }
            h1 {
                font-size: 3em;
                margin-bottom: 20px;
                text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
            }
            .status {
                background: rgba(46, 204, 113, 0.8);
                padding: 15px;
                border-radius: 8px;
                margin: 20px 0;
                font-weight: bold;
            }
            .info {
                background: rgba(52, 152, 219, 0.8);
                padding: 15px;
                border-radius: 8px;
                margin: 20px 0;
            }
            code {
                background: rgba(0, 0, 0, 0.3);
                padding: 5px 10px;
                border-radius: 4px;
                font-family: monospace;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 Zero Touch Cluster</h1>
            <div class="status">
                ✅ Cluster Deployment Successful!
            </div>
            <div class="info">
                <h3>What's Running:</h3>
                <p>✅ k3s Kubernetes Cluster</p>
                <p>✅ Hybrid Storage (local-path + NFS)</p>
                <p>✅ Monitoring Stack (Prometheus, Grafana)</p>
                <p>✅ ArgoCD GitOps</p>
                <p>✅ Sealed Secrets Management</p>
            </div>
            <div class="info">
                <h3>Next Steps:</h3>
                <p>Access Grafana: <code>kubectl port-forward -n monitoring svc/monitoring-grafana 3000:80</code></p>
                <p>Access ArgoCD: <code>kubectl port-forward -n argocd svc/argocd-server 8080:80</code></p>
                <p>Deploy your workloads: Update ArgoCD to point to your private Git repository</p>
            </div>
            <div class="info">
                <small>This is an example workload deployed by Zero Touch Cluster.<br>
                Ready to deploy your own applications via GitOps!</small>
            </div>
        </div>
    </body>
    </html>