apiVersion: v2
name: ztc-monitoring
description: Zero Touch Cluster monitoring stack for homelabs with Prometheus, Grafana, and AlertManager
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: ">=56.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled

maintainers:
  - name: ztc
    email: ztc@example.com

keywords:
  - monitoring
  - prometheus
  - grafana
  - alertmanager
  - homelab
  - k3s
  - zero-touch-cluster

home: https://github.com/yourname/homelab
sources:
  - https://github.com/yourname/homelab

annotations:
  category: Monitoring