apiVersion: v2
name: ztc-storage
description: Zero Touch Cluster hybrid storage solution for homelabs with local-path and optional NFS
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: ztc
    email: ztc@example.com

keywords:
  - storage
  - nfs
  - local-path
  - persistent-volumes
  - homelab
  - k3s
  - zero-touch-cluster

home: https://github.com/yourname/homelab
sources:
  - https://github.com/yourname/homelab

annotations:
  category: Storage