# Zero Touch Cluster Storage Configuration
# Hybrid storage with local-path (default) and optional Longhorn for homelabs

# Global configuration
global:
  # Default storage configuration
  defaultStorageClass: "local-path"

# Local Path Provisioner (k3s built-in)
# This is already installed with k3s, so we skip creation
localPath:
  enabled: false  # Don't create - k3s already provides this
  # k3s local-path is already the default storage class
  isDefaultClass: false

# Longhorn Storage (Cloud-Native Distributed Storage)
longhorn:
  enabled: false  # Longhorn disabled by default - enable for production clusters
  
  # Longhorn Helm chart configuration
  chart:
    repository: "https://charts.longhorn.io"
    name: "longhorn"
    version: "1.7.1"
    namespace: "longhorn-system"
  
  # Longhorn configuration
  config:
    # Default number of replicas for volumes
    defaultReplicaCount: 3
    
    # Default storage class
    defaultStorageClass:
      enabled: true
      isDefaultClass: false  # Don't override k3s local-path as default
      reclaimPolicy: "Delete"
      allowVolumeExpansion: true
      parameters:
        numberOfReplicas: "3"
        staleReplicaTimeout: "30"
        diskSelector: ""
        nodeSelector: ""
        recurringJobSelector: ""
    
    # Global settings
    settings:
      # Backup configuration
      backupTarget: ""  # Configure S3/NFS backup target if needed
      backupTargetCredentialSecret: ""
      
      # Performance settings
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      defaultDataPath: "/var/lib/longhorn/"
      
      # UI and authentication
      authenticationMethod: "none"  # Options: none, basic-auth, openid
      
    # Resource configuration
    resources:
      # Manager resources
      manager:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 200m
      
      # Driver resources  
      driver:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 128Mi
          cpu: 100m
      
      # UI resources
      ui:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 128Mi
          cpu: 100m

# Additional storage classes (can be extended)
additionalStorageClasses: []
#  - name: "fast-ssd"
#    provisioner: "kubernetes.io/no-provisioner"
#    volumeBindingMode: "WaitForFirstConsumer"
#    parameters:
#      type: "ssd"

# Example PVCs for testing (disabled by default)
examples:
  enabled: false
  
  # Example local-path PVC
  localPathPVC:
    name: "test-local-path"
    size: "1Gi"
    accessModes:
      - "ReadWriteOnce"
