apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-pvc
  namespace: $WORKLOAD_NAMESPACE
  labels:
    app: code-server
    app.kubernetes.io/name: code-server
    app.kubernetes.io/part-of: ztc-workloads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: $STORAGE_SIZE
  storageClassName: $STORAGE_CLASS
