metadata:
  name: "monitoring"
  description: "Complete homelab monitoring and dashboard solution"
  category: "essential"
  tags: ["monitoring", "dashboard", "homelab", "essential"]
  
workloads:
  - name: "uptime-kuma"
    priority: 1
    description: "Service health monitoring and status pages"
    overrides:
      STORAGE_CLASS: "nfs-client"
      MEMORY_LIMIT: "128Mi"
      HOSTNAME: "status.homelab.lan"

documentation:
  summary: "Deploys comprehensive service monitoring with enhanced ZTC dashboard integration"
  use_case: "Perfect for homelab operators who want professional service monitoring with the ZTC dashboard"
  access_urls:
    - "http://homelab.lan - ZTC Dashboard (automatically available)"
    - "http://status.homelab.lan - Service monitoring and uptime tracking"
  post_install:
    - "Configure Uptime Kuma to monitor your essential services"
    - "Access the main ZTC dashboard at http://homelab.lan for service directory"
    - "Uptime Kuma provides detailed monitoring and status pages"
    - "ZTC dashboard automatically shows Uptime Kuma status"
  
resource_requirements:
  total_memory: "128Mi"
  total_cpu: "75m"  
  total_storage: "2Gi"
  
benefits:
  - "24/7 monitoring of all homelab services"
  - "Integrated with ZTC dashboard for unified experience"
  - "Status pages for communicating service availability"
  - "Persistent monitoring configuration"