metadata:
  name: "starter"
  description: "Essential homelab starter pack - monitoring and organization"
  category: "essential"
  tags: ["starter", "beginner", "essential", "monitoring", "dashboard"]
  
workloads:
  - name: "uptime-kuma"  
    priority: 1
    description: "Monitor service health and create status pages"
    overrides:
      HOSTNAME: "status.homelab.lan"
      STORAGE_CLASS: "local-path"
      MEMORY_LIMIT: "128Mi"

documentation:
  summary: "Essential monitoring for new ZTC users - service health tracking with minimal resource usage"
  use_case: "Perfect for beginners who want to monitor their homelab services with minimal overhead"
  access_urls:
    - "http://homelab.lan - ZTC Dashboard (automatically available with core system)"
    - "http://status.homelab.lan - Service health monitoring"
  post_install:
    - "Configure Uptime Kuma to monitor your essential services"
    - "The ZTC dashboard at http://homelab.lan is automatically available"
    - "Uptime Kuma uses minimal resources - perfect for learning"
    - "Great foundation before adding more advanced workloads"
  
resource_requirements:
  total_memory: "128Mi"
  total_cpu: "50m"  
  total_storage: "1Gi"
  
benefits:
  - "Ultra-minimal resource usage for small clusters"
  - "Professional service health monitoring"
  - "Automated ZTC dashboard provides service directory"
  - "Foundation for more advanced monitoring"
  - "Fast deployment - running in under 2 minutes"