apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: $WORKLOAD_NAMESPACE
  labels:
    app: uptime-kuma
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/part-of: ztc-workloads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
      - name: init-permissions
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          if [ ! -d /app/data ]; then
            mkdir -p /app/data
          fi
          chown -R 1000:1000 /app/data
          chmod -R 755 /app/data
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: uptime-kuma-data
          mountPath: /app/data
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma:$IMAGE_TAG
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: UPTIME_KUMA_PORT
          value: "3001"
        - name: UPTIME_KUMA_HOST
          value: "$HOSTNAME"
        volumeMounts:
        - name: uptime-kuma-data
          mountPath: /app/data
        resources:
          requests:
            memory: $MEMORY_REQUEST
            cpu: $CPU_REQUEST
          limits:
            memory: $MEMORY_LIMIT
            cpu: $CPU_LIMIT
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: uptime-kuma-data
        persistentVolumeClaim:
          claimName: uptime-kuma-pvc
