apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-runner-cache-pvc
  namespace: $WORKLOAD_NAMESPACE
  labels:
    app: gitea-runner
    app.kubernetes.io/name: gitea-runner
    app.kubernetes.io/part-of: ztc-workloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: $STORAGE_CLASS
  resources:
    requests:
      storage: $STORAGE_SIZE