apiVersion: v2
name: ztc-homepage
description: Zero Touch Cluster entry point dashboard with service discovery and hot-reload
type: application
version: 2.0.0
appVersion: "v0.9.2"

maintainers:
  - name: ztc-team
    email: ztc@example.com

keywords:
  - dashboard
  - homepage
  - entry-point
  - portal
  - homelab
  - k3s
  - zero-touch-cluster

home: https://github.com/skol/ztc
sources:
  - https://github.com/skol/ztc
  - https://github.com/gethomepage/homepage

annotations:
  category: Core Infrastructure
  ztc.homelab/features: "service-discovery,hot-reload,kubernetes-integration,widgets"
  ztc.homelab/redesigned: "2024-12"
  ztc.homelab/changelog: |
    v2.0.0 (Redesign):
    - Removed persistence for hot-reload configuration updates
    - Fixed YAML generation and broken bookmarks/services
    - Added Kubernetes service discovery with auto-annotations
    - Enhanced widgets with cluster status and metrics
    - Added custom CSS theming and ZTC branding
    - Improved RBAC for comprehensive cluster monitoring
    - Eliminated default content flash on startup
    - Created Homepage workload template for custom instances