# ZTC Homepage - Entry Point Dashboard
# Pre-configured with ZTC services and branding

homepage:
  # ZTC Branding
  title: "Zero Touch Cluster"
  subtitle: "Your Kubernetes Homelab Platform"
  logo: "https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png"
  
  # Theme Configuration
  theme: "dark"
  color: "blue"
  headerStyle: "clean"
  hideVersion: true
  
  # Container Configuration
  image:
    repository: "ghcr.io/gethomepage/homepage"
    tag: "v1.3.2"
    pullPolicy: "IfNotPresent"
  
  puid: 1000
  pgid: 1000
  logLevel: "info"
  
  # Layout Configuration
  layout:
    Core Infrastructure:
      style: "row"
      columns: 3
    Applications:
      style: "row" 
      columns: 4
    Development:
      style: "row"
      columns: 3
    Monitoring:
      style: "row"
      columns: 2
  
  # ZTC Core Services with widgets for status monitoring
  services:
    - name: "Core Infrastructure"
      services:
        - name: "Gitea"
          icon: "gitea"
          href: "http://gitea.homelab.lan"
          description: "Git server and container registry"
          widget:
            type: "gitea"
            url: "http://gitea-http.gitea.svc.cluster.local:3000"
            key: "{{HOMEPAGE_VAR_GITEA_TOKEN}}"
        - name: "ArgoCD"
          icon: "argocd" 
          href: "http://argocd.homelab.lan"
          description: "GitOps continuous deployment"
          widget:
            type: "argocd"
            url: "http://argocd-server.argocd.svc.cluster.local"
            username: "admin"
            password: "{{HOMEPAGE_VAR_ARGOCD_TOKEN}}"
        - name: "Grafana"
          icon: "grafana"
          href: "http://grafana.homelab.lan" 
          description: "Monitoring and observability"
          widget:
            type: "grafana"
            url: "http://monitoring-grafana.monitoring.svc.cluster.local"
            username: "admin"
            password: "{{HOMEPAGE_VAR_GRAFANA_TOKEN}}"

  # ZTC Dashboard widgets with cluster status
  widgets:
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
        nodes:
          show: true
          cpu: true
          memory: true
    - search:
        provider: "duckduckgo"
        target: "_blank"
    - datetime:
        text_size: "xl"
        format:
          timeStyle: "short"
          dateStyle: "short"
          hourCycle: "h23"
    - resources:
        backend: "kubernetes"
        expanded: true
        cpu: true
        memory: true

  # Network Configuration
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "web"
    hosts:
      - host: "homelab.lan"  # Root domain entry point
        paths:
          - path: "/"
            pathType: "Prefix"
    tls: []

  # Resource Configuration
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  # Security Configuration
  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL

  # Health Checks
  probes:
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    readiness:
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

  # Persistence - DISABLED for config hot-reload support
  persistence:
    enabled: false
    storageClass: "local-path"
    size: "1Gi"
    accessModes:
      - "ReadWriteOnce"

  # RBAC for Kubernetes API access
  rbac:
    enabled: true

  # Additional environment variables for service discovery and config
  # We now explicitly map secret keys to the variables Homepage expects.
  extraEnv:
    - name: "HOMEPAGE_CONFIG_DIR"
      value: "/app/config"
    - name: "HOMEPAGE_LOG_LEVEL" 
      value: "debug"
    - name: "HOMEPAGE_ALLOWED_HOSTS"
      value: "homelab.lan"
      
    # Gitea API Token
    - name: "HOMEPAGE_VAR_GITEA_TOKEN"
      valueFrom:
        secretKeyRef:
          name: ztc-homepage-api-tokens
          key: GITEA_TOKEN

    # ArgoCD API Token
    - name: "HOMEPAGE_VAR_ARGOCD_TOKEN"
      valueFrom:
        secretKeyRef:
          name: ztc-homepage-api-tokens
          key: ARGOCD_TOKEN
          
    # Grafana API Token
    - name: "HOMEPAGE_VAR_GRAFANA_TOKEN"
      valueFrom:
        secretKeyRef:
          name: ztc-homepage-api-tokens
          key: GRAFANA_TOKEN