---
# Playbook to configure dedicated Kubernetes storage server

- name: Configure K8s Storage Server
  hosts: k8s_storage
  gather_facts: true
  vars_files:
    - ../inventory/secrets.yml
  
  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

  roles:
    - common
    - nfs-server

  post_tasks:
    - name: Display success message
      debug:
        msg: |
          ✅ K8s storage server configuration completed successfully!
          
          🎯 STORAGE CONFIGURATION:
          - Type: {{ storage_type | default('local-path') }}
          - Server IP: {{ k8s_storage_ip }}
          - Path: {{ local_storage_path | default('/opt/local-path-provisioner') }}
          
          🚀 READY FOR DEPLOYMENT:
          The storage node is configured and ready for k3s cluster deployment.
          Using built-in local-path provisioner for simplified storage management.
          
          Next: ansible-playbook ansible/playbooks/02-k3s-cluster.yml 