# ZTC Vaultwarden Configuration for System-Level Credential Management
# Optimized for homelab environments with focus on security and reliability

# Global ZTC configuration
global:
  namespace: vaultwarden
  domain: "vault.homelab.lan"

# Vaultwarden configuration
vaultwarden:
  enabled: true
  
  # Image configuration
  image:
    repository: vaultwarden/server
    tag: "1.32.0"  # Pinned version for stability
    pullPolicy: IfNotPresent
  
  # Admin configuration
  admin:
    # Admin token and credentials are managed via sealed secrets
    existingSecret: vaultwarden-admin-secret
    signupsAllowed: true  # Allow signups initially for setup
    
  # Server configuration
  config:
    domain: "http://vault.homelab.lan"
    websocketEnabled: true
    dataFolder: "/data"
    
    # Security settings
    rocket:
      tls: "{disabled=true}"  # TLS handled by Traefik
      port: 80
    
    # Feature configuration
    features:
      signupsAllowed: true
      invitationsAllowed: true
      passwordHintsAllowed: false
      showPasswordHint: false
      emailInvitations: false  # No email server needed for homelab
      
  # Resource configuration - optimized for homelab
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"  # Increased for system component
      cpu: "200m"
      
  # Probes for reliability
  livenessProbe:
    enabled: true
    httpGet:
      path: /alive
      port: 80
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
    
  readinessProbe:
    enabled: true
    httpGet:
      path: /alive
      port: 80
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# Storage configuration
storage:
  enabled: true
  size: "5Gi"  # Increased for system usage
  storageClass: "longhorn"  # Use distributed storage for system component
  accessMode: ReadWriteOnce
  
# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 80
  
# Ingress configuration
ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: vault.homelab.lan
      paths:
        - path: /
          pathType: Prefix
          
# Security context
securityContext:
  enabled: true
  fsGroup: 1000
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true

# Auto-population configuration for ZTC credentials
ztcIntegration:
  enabled: true
  
  # API configuration for credential population
  api:
    enabled: true
    timeout: 30
    retries: 3
    
  # Credential organization
  organization:
    name: "ZTC System Credentials"
    collections:
      system: "System Services"
      monitoring: "Monitoring Stack"
      gitops: "GitOps Services"
      
  # Services to populate automatically
  services:
    grafana:
      enabled: true
      url: "http://grafana.homelab.lan"
      folder: "monitoring"
    gitea:
      enabled: true
      url: "http://gitea.homelab.lan"
      folder: "gitops"
    argocd:
      enabled: true
      url: "http://argocd.homelab.lan"
      folder: "gitops"