apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-demo-pvc
  namespace: storage-demo
  labels:
    app.kubernetes.io/name: storage-demo
    app.kubernetes.io/part-of: ztc-examples
    storage-type: local-path
    example: "true"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-writer
  namespace: storage-demo
  labels:
    app.kubernetes.io/name: local-path-writer
    app.kubernetes.io/part-of: ztc-examples
    example: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: local-path-writer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local-path-writer
        app.kubernetes.io/part-of: ztc-examples
    spec:
      containers:
      - name: writer
        image: alpine:3.18
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "Local Path Storage Demo - ZTC" > /data/local-demo.txt
            echo "Node: $(hostname)" >> /data/local-demo.txt
            echo "Timestamp: $(date)" >> /data/local-demo.txt
            echo "Storage Class: local-path (fast local storage)" >> /data/local-demo.txt
            echo "Use case: Single-pod apps, logs, cache" >> /data/local-demo.txt
            while true; do
              echo "$(date): Local path storage working!" >> /data/local-demo.txt
              cat /data/local-demo.txt
              sleep 30
            done
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "16Mi"
            cpu: "5m"
          limits:
            memory: "32Mi"
            cpu: "20m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: local-path-demo-pvc