apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Target namespace for all resources
namespace: argocd

# ArgoCD installation using official manifests
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - argocd-server-ingress.yaml

# ConfigMap patches for insecure mode (since we're using ingress)
patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
      namespace: argocd
    patch: |-
      - op: add
        path: /data
        value:
          server.insecure: "true"