apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Default policy for homelab (can be customized)
  policy.default: role:readonly
  
  # Admin policy - full access
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, certificates, *, *, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, logs, get, *, allow
    p, role:admin, exec, create, */*, allow
    
    # Bind admin role to local admin user
    g, admin, role:admin
  
  # Optional: Scopes for OIDC/OAuth (uncomment if using external auth)
  # scopes: '[groups, email]'