---
# Handlers for k3s role

- name: restart k3s
  systemd:
    name: k3s
    state: restarted
    daemon_reload: true
  become: true
  listen: restart k3s

- name: restart k3s-agent
  systemd:
    name: k3s-agent
    state: restarted
    daemon_reload: true
  become: true
  listen: restart k3s-agent

- name: reload systemd
  systemd:
    daemon_reload: true
  become: true
  listen: reload systemd 