{{- if .Values.homepage.persistence.enabled }}
# NOTE: Persistence is disabled by default for config hot-reload support
# If you enable persistence, configuration updates will require pod deletion
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ztc-homepage.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ztc-homepage.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.homepage.persistence.accessModes | nindent 4 }}
  {{- if .Values.homepage.persistence.storageClass }}
  storageClassName: {{ .Values.homepage.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.homepage.persistence.size | quote }}
{{- end }}