apiVersion: v1
kind: Service
metadata:
  name: {{ include "ztc-homepage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ztc-homepage.labels" . | nindent 4 }}
  annotations:
    # Homepage service discovery
    ztc.homelab/homepage-enabled: "true"
    homepage.dev/enabled: "true"
    homepage.dev/name: {{ .Values.homepage.title | quote }}
    homepage.dev/description: {{ .Values.homepage.subtitle | quote }}
    homepage.dev/group: "Core Infrastructure"
    homepage.dev/icon: "mdi-view-dashboard"
    homepage.dev/href: "http://homelab.lan"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    {{- include "ztc-homepage.selectorLabels" . | nindent 4 }}