apiVersion: v1
kind: Service
metadata:
  name: {{ include "ztc-homepage.fullname" . }}
  namespace: homepage
  labels:
    {{- include "ztc-homepage.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    {{- include "ztc-homepage.selectorLabels" . | nindent 4 }}