apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ztc-homepage.fullname" . }}
  namespace: homepage
  labels:
    {{- include "ztc-homepage.labels" . | nindent 4 }}
automountServiceAccountToken: true