{{- if and .Values.vaultwarden.enabled .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ztc-vaultwarden.fullname" . }}-pvc
  namespace: {{ include "ztc-vaultwarden.namespace" . }}
  labels:
    {{- include "ztc-vaultwarden.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
{{- end }}